### ISSUE TITLE
成员管理页面成员联系方式显示异常

### ISSUE THREAD

**Issue by sols1st** [nbtca/Sunday#49]
![QQ图片20230311190816](https://user-images.githubusercontent.com/102133294/224480832-90842035-08c5-43fa-9b64-d6358c2665f2.png)

**Comment by wen-templari** [comment]
可能暂时把这一列去掉会好一点 @ZhouWR

**Comment by wen-templari** [comment]
![Image](https://github.com/nbtca/Sunday/assets/52404670/616b66e3-d50e-44f3-aa27-6701f7bb4a8a)

**Comment by wen-templari** [comment]
![Image](https://github.com/nbtca/Sunday/assets/52404670/1f0644cd-cb56-4cc2-9dcc-7a0b01ef81ba)
